
version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/share/nginx/html
    networks:
      - ai_network

  app:
    build: ./src
    command: gunicorn --workers=4 --bind 0.0.0.0:8000 app:app
    volumes:
      - ./src:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${ENCRYPTED_DB_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - ai_network

  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - ai_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - ai_network

  monitoring:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - ai_network

volumes:
  db_data:

networks:
  ai_network:
    driver: bridge
