
apiVersion: v1
kind: Service
metadata:
  name: ai-app-service
  labels:
    app: ai-app
spec:
  type: LoadBalancer
  selector:
    app: ai-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  loadBalancerIP: 192.168.1.100
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
